version: "3"

services:
  app:
    build: .
    ports:
      - 5000:5000
    command: python ./app.py

  alert_manager-service:
    image: prom/alertmanager
    container_name: alert-manager
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
    restart: always

  prometheus-service:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090 
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    restart: always

  node_exporter:
    image: prom/node-exporter
    container_name: node-exporter
    ports:
      - 9100:9100
    pid: host
    restart: always

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus-service
    ports:
      - 3001:3000
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
    restart: always
