# Generated by Selenium IDE
import pytest
import time
import json
import os
from selenium import webdriver
driver =webdriver.Chrome(executable_path=r'C:\\Users\\jeanp\\Downloads\\chatbot-deployment-main\\chromedriver.exe')
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestChat():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_chat(self):
    self.driver.get("http://127.0.0.1:5000/")
    self.driver.set_window_size(1562, 885)
    self.driver.find_element(By.CSS_SELECTOR, "button > img").click()
    self.driver.find_element(By.CSS_SELECTOR, "input").click()
    self.driver.find_element(By.CSS_SELECTOR, "input").send_keys("bonjour")
    self.driver.find_element(By.CSS_SELECTOR, ".chatbox__send--footer").click()
    self.driver.find_element(By.CSS_SELECTOR, ".chatbox__button").click()
  
