global:
  scrape_interval: 10s
  
  evaluation_interval: 10s
rule_files:
  - rules.yml
alerting:
  alertmanagers:
  - static_configs:
      - targets:
        - alert_manager-service:9093
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
        - localhost:9090

  - job_name: app
    static_configs:
      - targets: ['app:5000']

  - job_name: node
    static_configs:
      - targets: ['node-exporter:9100']
